[package]
name = "jit"
version = "0.1.0"
authors = ["Andy Freeland <andy@andyfreeland.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha-1 = "0.9.6"
uuid = { version = "0.8", features = ["v4"] }
flate2 = "1.0.20"
hex = "0.4.3"
chrono = "0.4.19"
anyhow = "1.0.40"
thiserror = "1.0.24"
