---

name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v1.4.0
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --no-fail-fast
      - name: Run clippy
        run: cargo clippy -- --deny clippy::all
      - name: Run rustfmt
        run: cargo fmt --all -- --check
